#!/bin/sh

echo 'S50amba_service is running'

export LD_LIBRARY_PATH=/glibc
#enable ipcbind and util_svc daemon
if [ -x /usr/bin/ipcbind ]; then
	/usr/bin/ipcbind -b
	if [ -x /usr/bin/util_svc ]; then
		/usr/bin/util_svc -b
	fi

	if [ -x /usr/bin/camctrlserver ]; then
		/usr/bin/camctrlserver
	fi
fi

#Enable Linux RPC Binder and Amba background Daemons.
if [ -x /usr/bin/rpcbind ]; then
	/usr/bin/rpcbind

#AmbaNetfifo Daemon
	if [ -x /usr/bin/AmbaNetFifoDaemon ]; then
		/usr/bin/AmbaNetFifoDaemon
	else
		echo 'Warning: "AmbaNetFifoDaemon" is not available!'
	fi

#AmbaEventNotify Daemon
	if [ -x /usr/bin/AmbaEventNotifyDaemon ]; then
		/usr/bin/AmbaEventNotifyDaemon
	else
		echo 'Warning: "AmbaEventNotifyDaemon" is not available!'
	fi

else
	echo 'Warning: "rpcbind" is not available!'
fi
export LD_LIBRARY_PATH=

echo 'S50amba_service is done'
