#!/bin/sh

amt_test=none

FACTORY_TEST_DIR=/tmp/EMMC/factory_test

AMT_TEST_FLAG_FILE=/tmp/EMMC/factory_test/AMT_TEST

if [ ! -d $FACTORY_TEST_DIR ]; then
    echo "directory $FACTORY_TEST_DIR doen not exist, create it"
    mkdir -p $FACTORY_TEST_DIR
fi

if [ $amt_test = y ]; then
    echo "enable amt test"
    if [ ! -e $AMT_TEST_FLAG_FILE ]; then
        echo "file $AMT_TEST_FLAG_FILE does not exist, create it"
        echo '' > $AMT_TEST_FLAG_FILE
    fi
elif [ $amt_test = n ]; then
    echo "disable amt test"
    if [ -e $AMT_TEST_FLAG_FILE ]; then
        echo "file $AMT_TEST_FLAG_FILE does exist, remove it"
        rm -f $AMT_TEST_FLAG_FILE
    fi
fi

exit 0
