#!/bin/sh

CLEAN_BLACKBOX_LOG_FLAG=/tmp/blackbox/clean_blackbox_log_flag

mkdir -p /tmp/lib /tmp/run /tmp/disk /tmp/log /tmp/ppp
mkdir -p /tmp/fuse /tmp/FL0 /tmp/SD0 /tmp/EMMC /tmp/NFZ /tmp/BACKUP

#for dnsmasq.leases
mkdir -p /var/lib/misc

mount -t ambafs a: /tmp/FL0
mount -t ambafs b: /tmp/BACKUP
mount -t ambafs d: /tmp/SD0

mount -t yaffs2 -o inband-tags,tags-ecc-off /dev/mtdblock24 /tmp/NFZ
if [ $? -ne 0 ]; then
    flash_erase /dev/mtd24 0 0
    mount -t yaffs2 -o inband-tags,tags-ecc-off /dev/mtdblock24 /tmp/NFZ
fi

cat /proc/mtd | grep mtd25
if [ $? == 0 ]; then
    mount -t yaffs2 -o inband-tags,tags-ecc-off /dev/mtdblock25 /tmp/EMMC
    if [ $? != 0 ]; then
        flash_erase /dev/mtd25 0 0
        mount -t yaffs2 -o inband-tags,tags-ecc-off /dev/mtdblock25 /tmp/EMMC
    fi
fi

cat /proc/mtd | grep mtd26
if [ $? == 0 ]; then
    mkdir -p /tmp/blackbox
    mount -t yaffs2 -o inband-tags,tags-ecc-off /dev/mtdblock26 /tmp/blackbox
    if [ $? != 0 ]; then
        flash_erase /dev/mtd26 0 0
        mount -t yaffs2 -o inband-tags,tags-ecc-off /dev/mtdblock26 /tmp/blackbox
    fi
fi

if [ -e $CLEAN_BLACKBOX_LOG_FLAG ]; then
    /usr/bin/delete_user_log.sh blackbox
    rm $CLEAN_BLACKBOX_LOG_FLAG
fi

if [ ! -d "/tmp/NFZ/log" ]; then
    mkdir -p /tmp/NFZ/log
fi

if [ ! -d "/tmp/blackbox/log" ]; then
    mkdir -p /tmp/blackbox/log
fi

mount --bind /tmp/blackbox/log /tmp/NFZ/log
mount -o remount,ro /tmp/NFZ

free_size=`df -h | grep blackbox | cut -d 'M' -f 3 | sed 's/^[ \t]*//g' | cut -d '.' -f 1`
if [ ${free_size} -le 2 ]; then
    ls /tmp/blackbox/log/system/ > /tmp/log_file
    rm -rf /tmp/blackbox/log/system/*
    mv /tmp/log_file /tmp/blackbox/log/system/syslog.log
fi
#zram swap
#echo 4M > /sys/block/zram0/disksize
#mkswap /dev/zram0
#swapon /dev/zram0

#for ar6004 WoWLAN
mount -t debugfs none /sys/kernel/debug/
