#!/bin/sh

echo 'S41mount is running'
# insmod amba vitual file system
# kernel_ver=$(uname -r)
# insmod lib/modules/$kernel_ver/kernel/fs/ambavfs/ambavfs.ko

#/dev/random does not work
ln -sf /dev/urandom /dev/random

ln -sf /etc/resolv.conf /etc/ppp/resolv.conf

#start ftpd binding on /tmp
#tcpsvd -vE 0.0.0.0 21 ftpd -w /tmp &


echo 'S41mount is done'
